name: Npm Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write   # required for OIDC
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Print npm version (diagnostic)
        run: npm -v

      - name: Ensure npm >= 11.5.1
        run: npm install -g npm@latest
      - run: npm publish